### ISSUE TITLE
Choice of default theme reset when printing

### ISSUE THREAD

**Issue by yjolivet** [jlguenego/angular-tools#1]
To reproduce the error, you must: 

- Set the Windows theme to Dark
- Use the Color-Scheme-Service in an Angular application and choose the Light theme
- Open the print panel (right click and print for example)

When the print panel opens, the listener defined in the syncWithUserPreferences() function of the Color-Scheme-Service receives an event telling it that the user's preferences have changed and the theme automatically switches back to dark mode.

https://github.com/jlguenego/angular-tools/blob/65788a76d2bfb1d06930ba02f72f512fe7d49b62/projects/jlg/src/lib/services/color-scheme.service.ts#L72

**Comment by jlguenego** [comment]
I can reproduce this bug. 
The solution: to create a BehaviorObject that reflect the OS dark/light preference. This behaviorObject will send a next only if the value change.

**Comment by jlguenego** [comment]
Fixed. Released in 0.0.14

**Comment by jlguenego** [comment]
oups. corrected distinct into distinctUntilChanged.

Fixed in 0.0.15

**Comment by jlguenego** [comment]
I retake the defect. It is not well corrected.

**Comment by jlguenego** [comment]
This time it is definitely working.
I added a "isDoingPrint" boolean and I disable the listener when printing.
ready to test in 0.0.16 or more.

**Comment by yjolivet** [comment]
I tested it and it works.

Thank you!

I close the issue.
